#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : powerline-fonts
Version  : 1.2
Release  : 10
URL      : http://localhost/cgit/projects/powerline-fonts/snapshot/powerline-fonts-1.2.tar.gz
Source0  : http://localhost/cgit/projects/powerline-fonts/snapshot/powerline-fonts-1.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 OFL-1.0 OFL-1.1
Requires: powerline-fonts-data

%description
Powerline fonts
===============
This repository contains pre-patched and adjusted fonts for usage with
the new Powerline plugin.

%package data
Summary: data components for the powerline-fonts package.
Group: Data

%description data
data components for the powerline-fonts package.


%prep
%setup -q -n powerline-fonts-1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510693757
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1510693757
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/fonts/X11/OTF/DroidSansMonoforPowerline.otf
/usr/share/fonts/X11/OTF/FuraMono-BoldPowerline.otf
/usr/share/fonts/X11/OTF/FuraMono-MediumPowerline.otf
/usr/share/fonts/X11/OTF/FuraMono-RegularPowerline.otf
/usr/share/fonts/X11/OTF/Inconsolata-dzforPowerline.otf
/usr/share/fonts/X11/OTF/Inconsolata-gforPowerline.otf
/usr/share/fonts/X11/OTF/InconsolataforPowerline.otf
/usr/share/fonts/X11/OTF/MesloLGLDZRegularforPowerline.otf
/usr/share/fonts/X11/OTF/MesloLGLRegularforPowerline.otf
/usr/share/fonts/X11/OTF/MesloLGMDZRegularforPowerline.otf
/usr/share/fonts/X11/OTF/MesloLGMRegularforPowerline.otf
/usr/share/fonts/X11/OTF/MesloLGSDZRegularforPowerline.otf
/usr/share/fonts/X11/OTF/MesloLGSRegularforPowerline.otf
/usr/share/fonts/X11/OTF/SauceCodePowerlineBlack.otf
/usr/share/fonts/X11/OTF/SauceCodePowerlineBold.otf
/usr/share/fonts/X11/OTF/SauceCodePowerlineExtraLight.otf
/usr/share/fonts/X11/OTF/SauceCodePowerlineLight.otf
/usr/share/fonts/X11/OTF/SauceCodePowerlineMedium.otf
/usr/share/fonts/X11/OTF/SauceCodePowerlineRegular.otf
/usr/share/fonts/X11/OTF/SauceCodePowerlineSemibold.otf
/usr/share/fonts/X11/TTF/AnonymicePowerline.ttf
/usr/share/fonts/X11/TTF/AnonymicePowerlineBold.ttf
/usr/share/fonts/X11/TTF/AnonymicePowerlineBoldItalic.ttf
/usr/share/fonts/X11/TTF/AnonymicePowerlineItalic.ttf
/usr/share/fonts/X11/TTF/DejaVuSansMonoBoldObliqueforPowerline.ttf
/usr/share/fonts/X11/TTF/DejaVuSansMonoBoldforPowerline.ttf
/usr/share/fonts/X11/TTF/DejaVuSansMonoObliqueforPowerline.ttf
/usr/share/fonts/X11/TTF/DejaVuSansMonoforPowerline.ttf
/usr/share/fonts/X11/TTF/LiterationMonoPowerline.ttf
/usr/share/fonts/X11/TTF/LiterationMonoPowerlineBold.ttf
/usr/share/fonts/X11/TTF/LiterationMonoPowerlineBoldItalic.ttf
/usr/share/fonts/X11/TTF/LiterationMonoPowerlineItalic.ttf
/usr/share/fonts/X11/TTF/MonofurBoldforPowerline.ttf
/usr/share/fonts/X11/TTF/MonofurItalicforPowerline.ttf
/usr/share/fonts/X11/TTF/MonofurforPowerline.ttf
/usr/share/fonts/X11/TTF/UbuntuMonoderivativePowerline.ttf
/usr/share/fonts/X11/TTF/UbuntuMonoderivativePowerlineBold.ttf
/usr/share/fonts/X11/TTF/UbuntuMonoderivativePowerlineBoldItalic.ttf
/usr/share/fonts/X11/TTF/UbuntuMonoderivativePowerlineItalic.ttf
